server:
  port: 8099
  max-http-header-size: 10240
  servlet:
    context-path: /faw
beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /pages
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jta:
    atomikos:
      properties:
        max-actives: -1
        max-timeout: 300000
        default-jta-timeout: 300000
        enable-logging: true

mybatis-plus:
  mapper-locations: classpath*:cn/stylefeng/guns/**/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true

log:
  path: _app_logs