
package cn.stylefeng.guns.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "execute_ptt", targetNamespace = "http://xmlns.oracle.com/JieFangCeShi/ERP/service1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExecutePtt {


    /**
     * 
     * @param part1
     * @return
     *     returns cn.stylefeng.guns.webservice.client.Resp
     */
    @WebMethod(action = "execute")
    @WebResult(name = "resp", targetNamespace = "", partName = "part1")
    public Resp execute(
        @WebParam(name = "req", targetNamespace = "", partName = "part1")
        Req part1);

}
